In [2]:
from geometry_msgs.msg import Transform, Vector3, Quaternion
from tf.transformations import *

t = tag\
b = baxter head camera\
r = realsense

Tbt = tag in baxter head camera frame\
Trt = tag in realsense frame\
Tbr = realsense in baxter head camera frame

In [3]:
# Tbt = Transform(translation=Vector3(x=-0.00080424, y=0.13821, z=1.1631),
#                 rotation=Quaternion(x=0.70979, y=0.68655, z=-0.15584, w=-0.02361))
# Tbt

In [19]:
pbt = translation_matrix([-0.00080424, 0.13821, 1.1631])
Rbt = quaternion_matrix([0.70979, 0.68655, -0.15584, -0.02361])
Tbt = concatenate_matrices(pbt, Rbt)
print("Tbt =\n", Tbt)
pbt

Tbt =
 [[ 8.72230051e-03  9.67257478e-01 -2.53647181e-01 -8.04240000e-04]
 [ 9.81975063e-01 -5.61798238e-02 -1.80468291e-01  1.38210000e-01]
 [-1.88809158e-01 -2.47501107e-01 -9.50312740e-01  1.16310000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


array([[ 0.0087223 ,  0.96725748, -0.25364718,  0.        ],
       [ 0.98197506, -0.05617982, -0.18046829,  0.        ],
       [-0.18880916, -0.24750111, -0.95031274,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [5]:
# Trt = Transform(translation=Vector3(x=0.091172, y=0.13873, z=1.3479),
#                 rotation=Quaternion(x=-0.69976, y=0.71181, z=0.0052353, w=0.060349))
# Trt

In [6]:
prt = translation_matrix([0.091172, 0.13873, 1.3479])
Rrt = quaternion_matrix([-0.69976, 0.71181, 0.0052353, 0.060349])
Trt = concatenate_matrices(prt, Rrt)
print("Trt =\n", Trt)

Trt =
 [[-0.01339473 -0.9968173   0.07858659  0.091172  ]
 [-0.99555353  0.02062387  0.09191207  0.13873   ]
 [-0.0932403  -0.07700602 -0.99266123  1.3479    ]
 [ 0.          0.          0.          1.        ]]


In [11]:
Tbr = Tbt @ inverse_matrix(Trt)
print("Tbr =\n", Tbr)

Tbr =
 [[-0.98422909 -0.01204816  0.1764878  -0.14728657]
 [ 0.02866534 -0.9953546   0.09191041  0.14979603]
 [ 0.1745606   0.09551998  0.98000231 -0.18701164]
 [ 0.          0.          0.          1.        ]]


In [17]:
vbr = translation_from_matrix(Tbr)
# type(Tbt)

qbr = quaternion_from_matrix(Tbr)

Tbr_ = Transform(translation=Vector3(x=vbr[0], y=vbr[1], z=vbr[2]),
                 rotation=Quaternion(x=qbr[0], y=qbr[1], z=qbr[2], w=qbr[3]))

print("Tbr_ =\n", Tbr_)

# ebr = euler_from_matrix(Tbr)

# ebr

Tbr_ =
 translation: 
  x: -0.1472865747272882
  y: 0.1497960282015105
  z: -0.1870116420679273
rotation: 
  x: 0.08820884012981547
  y: 0.047096118746598616
  z: 0.994935424732234
  w: 0.010230187429768183
