In [30]:
from geometry_msgs.msg import Transform, Vector3, Quaternion
from tf.transformations import *

t = tag
b = baxter
r = realsense

Tbt = tag in baxter head camera frame\
Trt = tag in realsense frame\
Tbr = realsense in baxter head camera frame

In [ ]:
# Tbt = Transform(translation=Vector3(x=-0.00080424, y=0.13821, z=1.1631),
#                 rotation=Quaternion(x=0.70979, y=0.68655, z=-0.15584, w=-0.02361))
# Tbt

In [31]:
pbt = translation_matrix([-0.00080424, 0.13821, 1.1631])
Rbt = quaternion_matrix([0.70979, 0.68655, -0.15584, -0.02361])
Tbt = concatenate_matrices(pbt, Rbt)
print("Tbt =\n", Tbt)

Tbt =
 [[ 8.72230051e-03  9.67257478e-01 -2.53647181e-01 -8.04240000e-04]
 [ 9.81975063e-01 -5.61798238e-02 -1.80468291e-01  1.38210000e-01]
 [-1.88809158e-01 -2.47501107e-01 -9.50312740e-01  1.16310000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [24]:
# Trt = Transform(translation=Vector3(x=0.091172, y=0.13873, z=1.3479),
#                 rotation=Quaternion(x=-0.69976, y=0.71181, z=0.0052353, w=0.060349))
# Trt

In [35]:
prt = translation_matrix([0.091172, 0.13873, 1.3479])
Rrt = quaternion_matrix([-0.69976, 0.71181, 0.0052353, 0.060349])
Trt = concatenate_matrices(prt, Rrt)
print("Trt =\n", Trt)

Trt =
 [[-0.01339473 -0.9968173   0.07858659  0.091172  ]
 [-0.99555353  0.02062387  0.09191207  0.13873   ]
 [-0.0932403  -0.07700602 -0.99266123  1.3479    ]
 [ 0.          0.          0.          1.        ]]


In [36]:
Tbr = Tbt * inverse_matrix(Trt)
print("Tbr =\n", Tbr)

Tbr =
 [[-1.16832878e-04 -9.62956595e-01  2.36501400e-02 -2.13134031e-04]
 [-9.78849730e-01 -1.15864531e-03  1.38971448e-02  2.65110403e-02]
 [-1.48378680e-02 -2.27483396e-02  9.43338614e-01  1.53307305e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [44]:
vbr = translation_from_matrix(Tbr)
qbr = quaternion_from_matrix(Tbr)

Tbr_ = Transform(translation=Vector3(x=vbr[0], y=vbr[1], z=vbr[2]),
                 rotation=Quaternion(x=qbr[0], y=qbr[1], z=qbr[2], w=qbr[3]))

print("Tbr_ =\n", Tbr_)

ebr = euler_from_matrix(Tbr)

ebr

Tbr_ =
 translation: 
  x: -0.00021313403086664937
  y: 0.026511040266107982
  z: 1.5330730545276134
rotation: 
  x: -0.013147972865170205
  y: 0.013809048846600454
  z: -0.005702271764183202
  w: 0.6967896267443657


(-0.02411003990034436, 0.015157312816261046, -1.5709156841120222)